version: '3.8'

services:
  web:
    image: tarunpatidar428/cattle_breed_app:latest
    container_name: cattle_breed_app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      PYTHONUNBUFFERED: "1"
      TWILIO_ACCOUNT_SID: "AC4be6a0fc5f7eb69e4d436e3fa65bebc7"
      TWILIO_AUTH_TOKEN: "b0b95f8925227b22975976df27727250"
      TWILIO_VERIFY_SERVICE_SID: "VA7969e6648ebd03905a90207650a320c0"
      # Point SQLAlchemy to the Postgres service
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://postgres:tarun@postgres:5432/Adhar"
      MODEL_PATH: "/app/resnet50_model.h5"
    volumes:
      - ./static/uploads:/app/static/uploads
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:17
    container_name: cattle_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tarun
      POSTGRES_DB: Adhar
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
